name: massai mara park 05 docker build

on:
  workflow_dispatch

jobs:
  mmpark01_docker_build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
            username: "${{ secrets.DOCKER_USERNAME }}"
            password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: docker operation
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/massai_mara:v2

          docker push ${{ secrets.DOCKER_USERNAME }}/massai_mara:v2

      - name: logout from docker hub
        if: always()
        run: docker logout
