name: massai mara park 01 multiple jobs

on:
  workflow_dispatch:

jobs:
  build:
    name: Build JAR
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*SNAPSHOT.jar

  deploy-and-test:
    name: Deploy and Test
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar

      - name: Run Spring Boot app in background
        run: |
          JAR_NAME=$(ls *SNAPSHOT.jar)
          echo "Running Spring Boot app: $JAR_NAME"
          nohup java -jar $JAR_NAME > app.log 2>&1 &
          echo "Waiting for app to start..."
          for i in {1..10}; do
            curl -s http://localhost:8080 && break
            echo "Waiting... ($i)"
            sleep 5
          done

      - name: Run test #1 - root endpoint
        run: curl -f http://localhost:8080

      - name: Run test #2 - images endpoint
        run: curl -f http://localhost:8080/images

      - name: Run test #3 - animal endpoint
        run: curl -f http://localhost:8080/animal

      - name: Show Spring Boot logs on failure
        if: failure()
        run: cat app.log
